#!/bin/ksh
#
# $OpenBSD$
#
# Xray-core installer for OpenBSD.
# Strictly follows hier(7), bsd.own.mk and rc.d(8) standards.
# Designed for doas/sudo + cron usage.

set -eu
umask 022

# ==================== CONFIGURATION (hier(7) compliant) ====================
BIN_PATH="/usr/local/bin/xray"
SHARE_PATH="/usr/local/share/xray"      # Architecture-independent geo assets
CONF_DIR="/etc/xray"
LOG_DIR="/var/log/xray"
RC_SCRIPT="/etc/rc.d/xray"
DAEMON_USER="_xray"
# daemon_class is READ-ONLY in rc.subr — it is automatically derived from
# the rc.d script name by searching login.conf(5) for a matching class.
# We define it here only as a shell variable for use in setup_login_class().
DAEMON_CLASS="xray"
GITHUB_REPO="XTLS/Xray-core"

# Script operation flags
QUIET=0
FORCE=0

# ========================================================================
# Sanity check: Ensure script is running with root privileges
if [ "$(id -u)" -ne 0 ]; then
    echo "error: This script requires root privileges. Please run using doas or sudo." >&2
    exit 1
fi

# OpenBSD native architecture detection for downloading the correct binary
case $(uname -m) in
    amd64)  XRAY_ARCH="64" ;;
    i386)   XRAY_ARCH="32" ;;
    arm64)  XRAY_ARCH="arm64-v8a" ;;
    *)      echo "error: Architecture $(uname -m) is currently not supported by Xray releases." >&2; exit 1 ;;
esac

# Cleanup function to remove temporary files upon script exit or interruption
cleanup() {
    [ -n "${TMP_DIR:-}" ] && [ -d "$TMP_DIR" ] && rm -rf "$TMP_DIR"
}
trap cleanup EXIT INT TERM

# Logging utilities
log()   { [ "$QUIET" -eq 1 ] && logger -t xray-install -p user.info "$1" || echo "info: $1"; }
error() { [ "$QUIET" -eq 1 ] && logger -t xray-install -p user.err "$1" || echo "error: $1" >&2; }

# POSIX/OpenBSD compliant version comparison (workaround since there is no GNU sort -V)
version_gt() {
    local top
    top=$(printf '%s\n%s\n' "$1" "$2" | sort -t. -k1,1n -k2,2n -k3,3n | head -n1)
    [ "$top" != "$1" ]
}

# Extracts the version number of the currently installed binary
get_current_version() {
    [ -x "$BIN_PATH" ] || { echo ""; return; }
    "$BIN_PATH" version 2>/dev/null | head -n1 | awk '{print $2}' | tr -d 'v'
}

# Queries GitHub API for the latest release tag
get_latest_version() {
    ftp -V -o - "https://api.github.com/repos/${GITHUB_REPO}/releases/latest" 2>/dev/null |
        awk -F'"' '/"tag_name":/ {print $4}' | tr -d 'v'
}

# Creates a dedicated, unprivileged user for running the daemon securely
create_daemon_user() {
    if ! id -u "$DAEMON_USER" >/dev/null 2>&1; then
        log "Creating dedicated system user '$DAEMON_USER' to isolate the daemon..."
        useradd -s /sbin/nologin -d /var/empty -c "Xray Proxy Service" "$DAEMON_USER"
    else
        log "System user '$DAEMON_USER' already exists, proceeding..."
    fi
}

# Adds the xray login class to /etc/login.conf if not already present.
# This is the correct way to set fd limits for rc.d daemons: rc.subr(8)
# automatically sets daemon_class to match the rc.d script name when a
# corresponding login class exists in login.conf(5). No manual daemon_class
# assignment in the rc.d script is needed or correct.
setup_login_class() {
    if grep -q "^${DAEMON_CLASS}:" /etc/login.conf 2>/dev/null; then
        log "Login class '${DAEMON_CLASS}' already exists in /etc/login.conf."
        return
    fi

    log "Appending '${DAEMON_CLASS}' login class to /etc/login.conf for fd limit tuning..."
    cat >> /etc/login.conf << EOF

${DAEMON_CLASS}:\\
        :openfiles-cur=4096:\\
        :openfiles-max=8192:\\
        :tc=daemon:
EOF
    cap_mkdb /etc/login.conf
    log "Rebuilt /etc/login.conf database via cap_mkdb(8)."
}

# Generates and installs the rc.d(8) service script.
# Key correctness notes:
#   - daemon_class is NOT set here; rc.subr sets it automatically from login.conf.
#   - ${_bg} MUST be placed outside the quoted string passed to ${rcexec}.
#     Inside quotes, it would be passed literally as arguments to the daemon
#     instead of being interpreted as shell redirection + backgrounding by ksh.
#   - rc_reload=NO because Xray does not support SIGHUP config reload.
install_rc_script() {
    log "Generating and installing OpenBSD rc.d(8) service script at $RC_SCRIPT..."
    cat > "$RC_SCRIPT" << EOF
#!/bin/ksh
#
# \$OpenBSD\$
#
# Xray-core daemon control script.
# Auto-generated by install-xray.sh

daemon="${BIN_PATH}"
daemon_flags="run -confdir ${CONF_DIR}"
daemon_user="${DAEMON_USER}"
daemon_timeout="60"

. /etc/rc.d/rc.subr

rc_bg=YES
rc_reload=NO

rc_start() {
	# XRAY_LOCATION_ASSET must be injected via env(1).
	# \${_bg} is intentionally placed OUTSIDE the quoted argument string:
	# inside quotes it would be passed as literal text to the daemon binary,
	# not interpreted as shell redirection and backgrounding by ksh(1).
	\${rcexec} "env XRAY_LOCATION_ASSET=${SHARE_PATH} \${daemon} \${daemon_flags}" \${_bg}
}

rc_cmd \$1
EOF
    chmod 555 "$RC_SCRIPT"
    chown root:wheel "$RC_SCRIPT"
}

install_xray() {
    local version="$1"

    log "Starting Xray-core deployment process..."

    if [ "$version" = "latest" ]; then
        log "Querying GitHub for the latest release version..."
        version=$(get_latest_version)
        [ -z "$version" ] && { error "Failed to fetch the latest version tag from GitHub API."; exit 1; }
        version="v${version}"
    elif [ "${version#v}" = "$version" ]; then
        version="v${version}"
    fi

    local current
    current=$(get_current_version)
    local target=${version#v}

    if [ -n "$current" ] && [ "$current" = "$target" ] && [ "$FORCE" -eq 0 ]; then
        log "Xray v${current} is already installed and matches the requested version."
        [ "$QUIET" -eq 0 ] && echo "Hint: Use '$0 install --force' if you need to cleanly reinstall."
        exit 0
    fi

    # ==================== DOWNLOAD & VERIFICATION ====================
    TMP_DIR=$(mktemp -d /tmp/xray.XXXXXX)
    local zip="${TMP_DIR}/xray.zip"
    local dgst="${TMP_DIR}/xray.zip.dgst"

    log "Downloading Xray release ${version} for architecture ${XRAY_ARCH}..."
    ftp -V -o "$zip" "https://github.com/${GITHUB_REPO}/releases/download/${version}/Xray-openbsd-${XRAY_ARCH}.zip" \
        || { error "Failed to download the Xray zip archive."; exit 1; }

    log "Downloading SHA256 signature file..."
    ftp -V -o "$dgst" "https://github.com/${GITHUB_REPO}/releases/download/${version}/Xray-openbsd-${XRAY_ARCH}.zip.dgst" \
        || { error "Failed to download the .dgst signature file."; exit 1; }

    log "Verifying package integrity via SHA256 checksum..."
    local expected actual
    expected=$(sed -n 's/.*256= *//p' "$dgst" | head -n1)
    actual=$(sha256 -q "$zip")
    if [ -z "$expected" ] || [ "$expected" != "$actual" ]; then
        error "CRITICAL: SHA256 checksum verification failed! Archive might be corrupted or compromised."
        exit 1
    fi
    log "Checksum verification passed successfully."

    log "Extracting archive contents..."
    unzip -q -o "$zip" -d "$TMP_DIR"

    # ==================== DEPLOYMENT ====================
    create_daemon_user
    setup_login_class

    log "Installing binary to $BIN_PATH..."
    install -m 555 -o root -g bin "${TMP_DIR}/xray" "$BIN_PATH"

    log "Deploying geo-assets to $SHARE_PATH..."
    install -d -m 755 -o root -g bin "$SHARE_PATH"
    install -m 644 -o root -g bin "${TMP_DIR}/geoip.dat" "${TMP_DIR}/geosite.dat" "$SHARE_PATH/"

    log "Configuring directory permissions..."
    # Config directory: root:_xray 750 — daemon reads, only root modifies
    install -d -m 750 -o root -g "$DAEMON_USER" "$CONF_DIR"
    chown -R root:"$DAEMON_USER" "$CONF_DIR"
    find "$CONF_DIR" -name '*.json' -exec chmod 640 {} + 2>/dev/null || true

    # Log directory: _xray:_xray 750 — daemon has full control over its logs
    install -d -m 750 -o "$DAEMON_USER" -g "$DAEMON_USER" "$LOG_DIR"

    install_rc_script

    # ==================== FINAL SYSTEM MESSAGES ====================
    if [ "$QUIET" -eq 0 ]; then
        echo ""
        echo "================================================================================"
        echo " Xray-core ${version} has been deployed successfully!"
        echo "--------------------------------------------------------------------------------"
        echo "   Executable  : $BIN_PATH"
        echo "   Geo Assets  : $SHARE_PATH/ (geoip.dat, geosite.dat)"
        echo "   Configs     : $CONF_DIR/ (root:_xray, 640 on *.json)"
        echo "   Logs        : $LOG_DIR/ (_xray:_xray 750)"
        echo "   rc.d script : $RC_SCRIPT"
        echo "   login class : ${DAEMON_CLASS} (openfiles 4096/8192, tc=daemon)"
        echo ""
        echo "   Enable service : doas rcctl enable xray"
        echo "   Start service  : doas rcctl start xray"
        echo "================================================================================"
    else
        logger -t xray-install -p user.notice "Successfully installed/updated Xray to ${version}"
    fi
}

check_update() {
    local current latest
    current=$(get_current_version)
    latest=$(get_latest_version)

    [ -z "$latest" ] && { error "Failed to fetch latest version data."; exit 1; }

    if [ -z "$current" ]; then
        [ "$QUIET" -eq 0 ] && echo "Xray is currently not installed. The latest available release is: v${latest}"
        exit 0
    fi

    if version_gt "$latest" "$current"; then
        [ "$QUIET" -eq 0 ] && echo "Update available! v${current} -> v${latest}"
        return 0  # update available
    else
        [ "$QUIET" -eq 0 ] && echo "Your Xray installation is fully up to date (v${current})."
        return 1  # already up to date
    fi
}

uninstall_xray() {
    local purge=${1:-0}
    log "Initiating Xray-core removal procedure..."

    # Gracefully stop and disable the service before removing files
    rcctl stop xray 2>/dev/null || true
    rcctl disable xray 2>/dev/null || true

    for p in "$BIN_PATH" "$SHARE_PATH" "$RC_SCRIPT"; do
        [ -e "$p" ] && rm -rf "$p" && log "Deleted system path: $p"
    done

    if [ "$purge" = 1 ]; then
        rm -rf "$CONF_DIR" "$LOG_DIR" 2>/dev/null || true
        log "Purged configuration directory: $CONF_DIR"
        log "Purged log directory: $LOG_DIR"

        if id -u "$DAEMON_USER" >/dev/null 2>&1; then
            userdel "$DAEMON_USER" 2>/dev/null || true
            log "Deleted system user: $DAEMON_USER"
        fi
    else
        echo "warning: User configurations ($CONF_DIR) and logs ($LOG_DIR) were preserved."
        echo "         To completely obliterate all traces, run: '$0 remove --purge'"
    fi

    log "Xray-core removal completed."
}

print_help() {
    cat << EOF
Usage: $0 <command> [options]

Commands:
  install [version]     Install or upgrade Xray-core (defaults to the latest release)
  check                 Check GitHub for available updates
  update                Silent auto-update if a newer version is available
  remove [--purge]      Uninstall Xray-core
  help                  Display this comprehensive help message

Options:
  --force, -f           Force reinstallation even if the exact version is already installed
  --quiet, -q           Enable quiet mode (suppresses stdout, logs to syslog; ideal for cron jobs)
  --purge               Obliterate configs, logs, and the dedicated user (only valid with 'remove')

Examples:
  doas $0 install
  doas $0 install v1.8.4
  0 4 * * * doas $0 update --quiet   # Recommended cron job schedule for automatic updates
EOF
}

# ====================== ARGUMENT PARSING & MAIN EXECUTION ======================
COMMAND="install"
VERSION="latest"
PURGE=0

# Determine primary command
if [ $# -gt 0 ] && [ "${1#-}" = "$1" ]; then
    COMMAND="$1"
    shift
fi

# Parse additional runtime options
while [ $# -gt 0 ]; do
    case "$1" in
        --quiet|-q) QUIET=1; shift ;;
        --force|-f) FORCE=1; shift ;;
        --purge)    PURGE=1; shift ;;
        -*)         error "Unrecognized option '$1' provided."; print_help >&2; exit 1 ;;
        *)          VERSION="$1"; shift ;;
    esac
done

# Route to the appropriate function based on the requested command
case "$COMMAND" in
    install)
        if ! command -v unzip >/dev/null 2>&1; then
            log "Dependency 'unzip' is missing. Installing via pkg_add..."
            pkg_add -I unzip || { error "Failed to install required dependency: unzip."; exit 1; }
        fi
        install_xray "$VERSION"
        ;;
    check)
        check_update
        ;;
    update)
        # check_update now returns 0 if update available, 1 if already current.
        # This fixes the previous logic where check_update always returned 0.
        QUIET=1
        if check_update; then
            log "Auto-update triggered via cron/manual execution."
            install_xray latest
            rcctl restart xray 2>/dev/null || true
        fi
        ;;
    remove)
        uninstall_xray "$PURGE"
        ;;
    help)
        print_help
        ;;
    *)
        error "Unknown command '$COMMAND' requested."
        print_help >&2
        exit 1
        ;;
esac
